#!/usr/bin/groovy 
pipeline {
  agent none
  stages {
    stage ('Fast finish') {
      agent any
      steps {
        echo 'This will check for a fast finish'
      }
    }
    stage ('build') {
      paralell {
        stage('linux_python2.7') {
          agent any
          environment {
            CONFIG='linux_python2.7'
          }
          steps(){
            echo 'call conda-build here'
          }
        }
      }
    }
  }
}
