#!/usr/bin/groovy
pipeline {
  agent none
  stages {
   stage('build') {
      parallel {
        stage('linux_python2.7') {
          agent {
            label 'condaforge/linux-anvil'
          }
          environment {
            CONFIG="${STAGE_NAME}"
            FEEDSTOCK_ROOT="${WORKSPACE}"
            RECIPE_ROOT="${WORKSPACE}/recipe"
          }
          steps {
            sh """#!/bin/bash -il
               conda activate base
               .circleci/build_steps.sh
               """
          }
        }
        stage('linux_python3.6') {
          agent {
            label 'condaforge/linux-anvil'
          }
          environment {
            CONFIG="${STAGE_NAME}"
            FEEDSTOCK_ROOT="${WORKSPACE}"
            RECIPE_ROOT="${WORKSPACE}/recipe"
          }
          steps {
            sh """#!/bin/bash -il
               conda activate base
               .circleci/build_steps.sh
               """
          }
        }
      }
    }
  }
}
