#!/usr/bin/groovy 
pipeline {
  agent none
  stages {
    stage('fast-finish') {
      agent any
      steps {
        echo 'try to fast-finish'
      }
    }
    stage('build') {
      parallel {
        stage('linux_python2.7') {
          agent any
          environment {
            CONDA_HOME=tool name: 'miniconda3', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
          }
          steps {
            echo 'call conda-build here'
          }
        }
        stage('linux_python3.6') {
          agent any
          environment {
            CONDA_HOME=tool name: 'miniconda3', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
          }
          steps {
            echo 'call conda-build here'
          }
        }
      }
    }
  }
}
